update checklist
nielstiben/MLOPS-Project pull request #21
Opened 2022-01-18 14:29 UTC by nielstiben

2022-01-18 15:09 UTC, jaschn commented
@nielstiben please fix test

2022-01-19 10:33 UTC, denisramiros requested changes

2022-01-19 10:33 UTC, denisramiros commented on CHECKLIST.md
> +- [X] Deployed your model locally using TorchServe
We havent really done this one, so unmark

2022-01-19 10:54 UTC, denisramiros approved these changes

2022-01-19 10:54 UTC, merged